// Code generated by goyacc -l -o parser_gen.go -p cw grammar.y. DO NOT EDIT.
package cmdwire

import __yyfmt__ "fmt"

type cwSymType struct {
	yys    int
	text   string
	field  Field
	fields []Field
	tail   parsedTail
}

const REQUEST = 57346
const OK_TOKEN = 57347
const ERR = 57348
const NOTICE_TOKEN = 57349
const EVENT_TOKEN = 57350
const ITEM_TOKEN = 57351
const CHUNK_TOKEN = 57352
const COMMAND_TOKEN = 57353
const PATH_TOKEN = 57354
const FIELD_TOKEN = 57355
const CODE_FIELD = 57356
const SCHEMA_FIELD = 57357
const COUNT_FIELD = 57358

var cwToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"REQUEST",
	"OK_TOKEN",
	"ERR",
	"NOTICE_TOKEN",
	"EVENT_TOKEN",
	"ITEM_TOKEN",
	"CHUNK_TOKEN",
	"COMMAND_TOKEN",
	"PATH_TOKEN",
	"FIELD_TOKEN",
	"CODE_FIELD",
	"SCHEMA_FIELD",
	"COUNT_FIELD",
}

var cwStatenames = [...]string{}

const cwEofCode = 1
const cwErrCode = 2
const cwInitialStackSize = 16

var cwExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const cwPrivate = 57344

const cwLast = 41

var cwAct = [...]int8{
	23, 28, 31, 22, 20, 16, 24, 19, 17, 19,
	18, 21, 30, 19, 15, 18, 14, 25, 29, 27,
	26, 13, 29, 32, 12, 33, 11, 10, 9, 1,
	0, 0, 29, 34, 2, 3, 4, 5, 6, 7,
	8,
}

var cwPact = [...]int16{
	30, -32768, 17, 16, 15, 13, 10, 5, 3, -4,
	-11, -3, -6, -6, -4, -6, -32768, 0, -1, -32768,
	-14, 0, -32768, -1, 0, -32768, -32768, -32768, -32768, -1,
	-32768, 0, -32768, -1, -32768,
}

var cwPgo = [...]int8{
	0, 1, 0, 5, 3, 29,
}

var cwR1 = [...]int8{
	0, 5, 5, 5, 5, 5, 5, 5, 3, 3,
	3, 4, 4, 1, 1, 2, 2,
}

var cwR2 = [...]int8{
	0, 3, 5, 4, 3, 3, 3, 3, 0, 2,
	1, 1, 2, 0, 1, 1, 2,
}

var cwChk = [...]int16{
	-32768, -5, 4, 5, 6, 7, 8, 9, 10, 11,
	11, 11, 11, 11, 11, 11, -3, 12, -2, 13,
	15, 14, -4, -2, 12, -4, -3, -4, -1, -2,
	13, 16, -1, -2, -1,
}

var cwDef = [...]int8{
	0, -2, 0, 0, 0, 0, 0, 0, 0, 8,
	0, 0, 0, 0, 8, 0, 1, 13, 10, 15,
	0, 13, 4, 11, 0, 5, 6, 7, 9, 14,
	16, 13, 3, 12, 2,
}

var cwTok1 = [...]int8{
	1,
}

var cwTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16,
}

var cwTok3 = [...]int8{
	0,
}

var cwErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	cwDebug        = 0
	cwErrorVerbose = false
)

type cwLexer interface {
	Lex(lval *cwSymType) int
	Error(s string)
}

type cwParser interface {
	Parse(cwLexer) int
	Lookahead() int
}

type cwParserImpl struct {
	lval  cwSymType
	stack [cwInitialStackSize]cwSymType
	char  int
}

func (p *cwParserImpl) Lookahead() int {
	return p.char
}

func cwNewParser() cwParser {
	return &cwParserImpl{}
}

const cwFlag = -32768

func cwTokname(c int) string {
	if c >= 1 && c-1 < len(cwToknames) {
		if cwToknames[c-1] != "" {
			return cwToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func cwStatname(s int) string {
	if s >= 0 && s < len(cwStatenames) {
		if cwStatenames[s] != "" {
			return cwStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func cwErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !cwErrorVerbose {
		return "syntax error"
	}

	for _, e := range cwErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + cwTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(cwPact[state])
	for tok := TOKSTART; tok-1 < len(cwToknames); tok++ {
		if n := base + tok; n >= 0 && n < cwLast && int(cwChk[int(cwAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if cwDef[state] == -2 {
		i := 0
		for cwExca[i] != -1 || int(cwExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; cwExca[i] >= 0; i += 2 {
			tok := int(cwExca[i])
			if tok < TOKSTART || cwExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if cwExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += cwTokname(tok)
	}
	return res
}

func cwlex1(lex cwLexer, lval *cwSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(cwTok1[0])
		goto out
	}
	if char < len(cwTok1) {
		token = int(cwTok1[char])
		goto out
	}
	if char >= cwPrivate {
		if char < cwPrivate+len(cwTok2) {
			token = int(cwTok2[char-cwPrivate])
			goto out
		}
	}
	for i := 0; i < len(cwTok3); i += 2 {
		token = int(cwTok3[i+0])
		if token == char {
			token = int(cwTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(cwTok2[1]) /* unknown char */
	}
	if cwDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", cwTokname(token), uint(char))
	}
	return char, token
}

func cwParse(cwlex cwLexer) int {
	return cwNewParser().Parse(cwlex)
}

func (cwrcvr *cwParserImpl) Parse(cwlex cwLexer) int {
	var cwn int
	var cwVAL cwSymType
	var cwDollar []cwSymType
	_ = cwDollar // silence set and not used
	cwS := cwrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	cwstate := 0
	cwrcvr.char = -1
	cwtoken := -1 // cwrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		cwstate = -1
		cwrcvr.char = -1
		cwtoken = -1
	}()
	cwp := -1
	goto cwstack

ret0:
	return 0

ret1:
	return 1

cwstack:
	/* put a state and value onto the stack */
	if cwDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", cwTokname(cwtoken), cwStatname(cwstate))
	}

	cwp++
	if cwp >= len(cwS) {
		nyys := make([]cwSymType, len(cwS)*2)
		copy(nyys, cwS)
		cwS = nyys
	}
	cwS[cwp] = cwVAL
	cwS[cwp].yys = cwstate

cwnewstate:
	cwn = int(cwPact[cwstate])
	if cwn <= cwFlag {
		goto cwdefault /* simple state */
	}
	if cwrcvr.char < 0 {
		cwrcvr.char, cwtoken = cwlex1(cwlex, &cwrcvr.lval)
	}
	cwn += cwtoken
	if cwn < 0 || cwn >= cwLast {
		goto cwdefault
	}
	cwn = int(cwAct[cwn])
	if int(cwChk[cwn]) == cwtoken { /* valid shift */
		cwrcvr.char = -1
		cwtoken = -1
		cwVAL = cwrcvr.lval
		cwstate = cwn
		if Errflag > 0 {
			Errflag--
		}
		goto cwstack
	}

cwdefault:
	/* default state action */
	cwn = int(cwDef[cwstate])
	if cwn == -2 {
		if cwrcvr.char < 0 {
			cwrcvr.char, cwtoken = cwlex1(cwlex, &cwrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if cwExca[xi+0] == -1 && int(cwExca[xi+1]) == cwstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			cwn = int(cwExca[xi+0])
			if cwn < 0 || cwn == cwtoken {
				break
			}
		}
		cwn = int(cwExca[xi+1])
		if cwn < 0 {
			goto ret0
		}
	}
	if cwn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			cwlex.Error(cwErrorMessage(cwstate, cwtoken))
			Nerrs++
			if cwDebug >= 1 {
				__yyfmt__.Printf("%s", cwStatname(cwstate))
				__yyfmt__.Printf(" saw %s\n", cwTokname(cwtoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for cwp >= 0 {
				cwn = int(cwPact[cwS[cwp].yys]) + cwErrCode
				if cwn >= 0 && cwn < cwLast {
					cwstate = int(cwAct[cwn]) /* simulate a shift of "error" */
					if int(cwChk[cwstate]) == cwErrCode {
						goto cwstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if cwDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", cwS[cwp].yys)
				}
				cwp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if cwDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", cwTokname(cwtoken))
			}
			if cwtoken == cwEofCode {
				goto ret1
			}
			cwrcvr.char = -1
			cwtoken = -1
			goto cwnewstate /* try again in the same state */
		}
	}

	/* reduction by production cwn */
	if cwDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", cwn, cwStatname(cwstate))
	}

	cwnt := cwn
	cwpt := cwp
	_ = cwpt // guard against "declared and not used"

	cwp -= int(cwR2[cwn])
	// cwp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if cwp+1 >= len(cwS) {
		nyys := make([]cwSymType, len(cwS)*2)
		copy(nyys, cwS)
		cwS = nyys
	}
	cwVAL = cwS[cwp+1]

	/* consult goto table to find next state */
	cwn = int(cwR1[cwn])
	cwg := int(cwPgo[cwn])
	cwj := cwg + cwS[cwp].yys + 1

	if cwj >= cwLast {
		cwstate = int(cwAct[cwg])
	} else {
		cwstate = int(cwAct[cwj])
		if int(cwChk[cwstate]) != -cwn {
			cwstate = int(cwAct[cwg])
		}
	}
	// dummy call; replaced with literal code
	switch cwnt {

	case 1:
		cwDollar = cwS[cwpt-3 : cwpt+1]
		{
			setParsedRecord(cwlex, Record{
				Kind: Request, Command: cwDollar[2].text, Resource: cwDollar[3].tail.resource, Fields: cwDollar[3].tail.fields,
			})
		}
	case 2:
		cwDollar = cwS[cwpt-5 : cwpt+1]
		{
			fields := append([]Field{cwDollar[3].field, cwDollar[4].field}, cwDollar[5].fields...)
			setParsedRecord(cwlex, Record{Kind: OK, Command: cwDollar[2].text, Fields: fields})
		}
	case 3:
		cwDollar = cwS[cwpt-4 : cwpt+1]
		{
			fields := append([]Field{cwDollar[3].field}, cwDollar[4].fields...)
			setParsedRecord(cwlex, Record{Kind: Error, Command: cwDollar[2].text, Fields: fields})
		}
	case 4:
		cwDollar = cwS[cwpt-3 : cwpt+1]
		{
			setParsedRecord(cwlex, Record{
				Kind: Notice, Command: cwDollar[2].text, Resource: cwDollar[3].tail.resource, Fields: cwDollar[3].tail.fields,
			})
		}
	case 5:
		cwDollar = cwS[cwpt-3 : cwpt+1]
		{
			setParsedRecord(cwlex, Record{
				Kind: Event, Command: cwDollar[2].text, Resource: cwDollar[3].tail.resource, Fields: cwDollar[3].tail.fields,
			})
		}
	case 6:
		cwDollar = cwS[cwpt-3 : cwpt+1]
		{
			setParsedRecord(cwlex, Record{
				Kind: Item, Command: cwDollar[2].text, Resource: cwDollar[3].tail.resource, Fields: cwDollar[3].tail.fields,
			})
		}
	case 7:
		cwDollar = cwS[cwpt-3 : cwpt+1]
		{
			setParsedRecord(cwlex, Record{
				Kind: Chunk, Command: cwDollar[2].text, Resource: cwDollar[3].tail.resource, Fields: cwDollar[3].tail.fields,
			})
		}
	case 8:
		cwDollar = cwS[cwpt-0 : cwpt+1]
		{
			cwVAL.tail = parsedTail{}
		}
	case 9:
		cwDollar = cwS[cwpt-2 : cwpt+1]
		{
			cwVAL.tail = parsedTail{resource: cwDollar[1].text, fields: cwDollar[2].fields}
		}
	case 10:
		cwDollar = cwS[cwpt-1 : cwpt+1]
		{
			cwVAL.tail = parsedTail{fields: cwDollar[1].fields}
		}
	case 11:
		cwDollar = cwS[cwpt-1 : cwpt+1]
		{
			cwVAL.tail = parsedTail{fields: cwDollar[1].fields}
		}
	case 12:
		cwDollar = cwS[cwpt-2 : cwpt+1]
		{
			cwVAL.tail = parsedTail{resource: cwDollar[1].text, fields: cwDollar[2].fields}
		}
	case 13:
		cwDollar = cwS[cwpt-0 : cwpt+1]
		{
			cwVAL.fields = nil
		}
	case 14:
		cwDollar = cwS[cwpt-1 : cwpt+1]
		{
			cwVAL.fields = cwDollar[1].fields
		}
	case 15:
		cwDollar = cwS[cwpt-1 : cwpt+1]
		{
			cwVAL.fields = []Field{cwDollar[1].field}
		}
	case 16:
		cwDollar = cwS[cwpt-2 : cwpt+1]
		{
			cwVAL.fields = append(cwDollar[1].fields, cwDollar[2].field)
		}
	}
	goto cwstack /* stack new state and value */
}
