// Package schemagen generates typed Go bindings for cmdwire command schemas.
package schemagen

import (
	"bytes"
	"fmt"
	"go/format"
	"go/token"
	"strconv"
	"strings"
	"unicode"

	"github.com/sartura/cmdwire"
)

// Go generates one Go source file containing bindings for schemas.
func Go(packageName string, schemas []cmdwire.Schema) ([]byte, error) {
	if packageName == "" {
		return nil, fmt.Errorf("package name is empty")
	}
	seen := make(map[string]bool, len(schemas))
	seenNames := make(map[string]string, len(schemas))
	for _, schema := range schemas {
		if err := schema.Validate(); err != nil {
			return nil, err
		}
		if schema.Format != 1 {
			return nil, fmt.Errorf("generated Go supports schema format 1, got %d for %q", schema.Format, schema.Command)
		}
		if seen[schema.Command] {
			return nil, fmt.Errorf("repeated command schema %q", schema.Command)
		}
		generatedName := identifier(schema.Command)
		if err := addGoName(seenNames, generatedName, schema.Command, "command"); err != nil {
			return nil, err
		}
		if err := checkGoNames(schema); err != nil {
			return nil, err
		}
		for _, field := range schema.Request.Fields {
			if field.Unavailable {
				return nil, fmt.Errorf("generated Go does not support unavailable request field %q", field.Name)
			}
		}
		for _, record := range schema.Reply.Records {
			for _, field := range record.Fields {
				if err := checkGeneratedField(field); err != nil {
					return nil, err
				}
			}
		}
		for _, field := range schema.Reply.Terminal {
			if err := checkGeneratedField(field); err != nil {
				return nil, err
			}
		}
		seen[schema.Command] = true
	}

	var output bytes.Buffer
	fmt.Fprintln(&output, "// Code generated by cmdwire; DO NOT EDIT.")
	fmt.Fprintf(&output, "package %s\n\n", packageName)
	fmt.Fprintln(&output, "import (")
	if goUsesFmt(schemas) {
		fmt.Fprintln(&output, `"fmt"`)
	}
	fmt.Fprintln(&output, `"strconv"
"strings"

"github.com/sartura/cmdwire"
)`)
	fmt.Fprint(&output, `
func uint64Pointer(value uint64) *uint64 { return &value }

type UintValue struct {
    Value uint64
    Available bool
}

func Uint(value uint64) UintValue { return UintValue{Value: value, Available: true} }
func UnavailableUint() UintValue { return UintValue{} }

func formatRecords(records []cmdwire.Record) (string, error) {
    var output strings.Builder
    for index, record := range records {
        line, err := cmdwire.Format(record)
        if err != nil { return "", err }
        if index != 0 { output.WriteByte('\n') }
        output.WriteString(line)
    }
    return output.String(), nil
}

func field(record cmdwire.Record, name string) string {
    value, _ := record.Field(name)
    return value
}
`)

	for _, schema := range schemas {
		generateSchema(&output, schema)
	}

	generated, err := format.Source(output.Bytes())
	if err != nil {
		return nil, fmt.Errorf("formatting generated Go: %w\n%s", err, output.Bytes())
	}
	return generated, nil
}

func checkGeneratedField(field cmdwire.FieldSchema) error {
	if field.Type == "bytes" {
		return fmt.Errorf("generated Go does not support bytes field %q", field.Name)
	}
	if field.Unavailable && field.Type != "uint" {
		return fmt.Errorf("generated Go supports unavailable only for uint field %q", field.Name)
	}
	if field.Type == "hex" && field.Width > 16 {
		return fmt.Errorf("generated Go hex field %q exceeds 64 bits", field.Name)
	}
	return nil
}

func checkGoNames(schema cmdwire.Schema) error {
	requestNames := make(map[string]string, len(schema.Request.Fields))
	for _, field := range schema.Request.Fields {
		if err := addGoName(requestNames, identifier(field.Name), field.Name, "request field"); err != nil {
			return err
		}
	}

	replyNames := make(map[string]string)
	for index, record := range schema.Reply.Records {
		for _, field := range record.Fields {
			source := fmt.Sprintf("reply record %d field %q", index, field.Name)
			if record.Resource != "" {
				source = fmt.Sprintf("reply resource %q field %q", record.Resource, field.Name)
			}
			if err := addGoName(replyNames, replyFieldName(index, record, field), source, "reply field"); err != nil {
				return err
			}
		}
	}
	for _, field := range schema.Reply.Terminal {
		source := fmt.Sprintf("terminal field %q", field.Name)
		if err := addGoName(replyNames, "Terminal"+identifier(field.Name), source, "reply field"); err != nil {
			return err
		}
	}

	errorNames := make(map[string]string, len(schema.Errors))
	for _, errorSchema := range schema.Errors {
		name := identifier(strings.ToLower(errorSchema.Code))
		if err := addGoName(errorNames, name, errorSchema.Code, "error code"); err != nil {
			return err
		}
	}
	return nil
}

func addGoName(seen map[string]string, name, source, context string) error {
	if !token.IsIdentifier(name) {
		return fmt.Errorf("generated Go %s name %q for %q is not an identifier", context, name, source)
	}
	if previous, ok := seen[name]; ok {
		return fmt.Errorf("generated Go %s name %q collides for %q and %q", context, name, previous, source)
	}
	seen[name] = source
	return nil
}

func goUsesFmt(schemas []cmdwire.Schema) bool {
	for _, schema := range schemas {
		for _, record := range schema.Reply.Records {
			for _, field := range record.Fields {
				if field.Type == "hex" || hasValueValidation(field) {
					return true
				}
			}
		}
		for _, field := range schema.Reply.Terminal {
			if field.Type == "hex" || hasValueValidation(field) {
				return true
			}
		}
	}
	return false
}

func generateSchema(output *bytes.Buffer, schema cmdwire.Schema) {
	name := identifier(schema.Command)
	fmt.Fprintf(output, "const Command%s = %q\n\n", name, schema.Command)
	fmt.Fprintf(output, "var Schema%s = ", name)
	writeSchema(output, schema)
	fmt.Fprint(output, "\n\n")

	if len(schema.Errors) != 0 {
		fmt.Fprintf(output, "type %sErrorCode string\n\n", name)
		fmt.Fprintln(output, "const (")
		for _, errorSchema := range schema.Errors {
			fmt.Fprintf(output, "Error%s%s %sErrorCode = %q\n", name, identifier(strings.ToLower(errorSchema.Code)), name, errorSchema.Code)
		}
		fmt.Fprintln(output, ")")
		fmt.Fprintf(output, "func Format%sError(code %sErrorCode, diagnostics ...cmdwire.Field) (string, error) {\n", name, name)
		fmt.Fprintln(output, "fields := []cmdwire.Field{{Name: \"code\", Value: string(code)}}")
		fmt.Fprintln(output, "fields = append(fields, diagnostics...)")
		fmt.Fprintf(output, "record := cmdwire.Record{Kind: cmdwire.Error, Command: Command%s, Fields: fields}\n", name)
		fmt.Fprintf(output, "if err := Schema%s.ValidateError(record); err != nil { return \"\", err }\n", name)
		fmt.Fprintln(output, "return cmdwire.Format(record)")
		fmt.Fprint(output, "}\n\n")
	}

	fmt.Fprintf(output, "type %sRequest struct {\n", name)
	for _, field := range schema.Request.Fields {
		fmt.Fprintf(output, "%s %s\n", identifier(field.Name), goType(field))
	}
	fmt.Fprint(output, "}\n\n")
	fmt.Fprintf(output, "func Decode%s(record cmdwire.Record) (request %sRequest, err error) {\n", name, name)
	fmt.Fprintf(output, "if err = Schema%s.ValidateRequest(record); err != nil { return }\n", name)
	for _, fieldSchema := range schema.Request.Fields {
		writeDecodeField(output, "request."+identifier(fieldSchema.Name), fieldSchema)
	}
	fmt.Fprint(output, "return\n}\n\n")

	fmt.Fprintf(output, "type %sReply struct {\n", name)
	for index, record := range schema.Reply.Records {
		for _, field := range record.Fields {
			fmt.Fprintf(output, "%s %s\n", replyFieldName(index, record, field), goType(field))
		}
	}
	for _, field := range schema.Reply.Terminal {
		fmt.Fprintf(output, "Terminal%s %s\n", identifier(field.Name), goType(field))
	}
	fmt.Fprint(output, "}\n\n")

	fmt.Fprintf(output, "func (reply %sReply) Records() []cmdwire.Record {\n", name)
	fmt.Fprintf(output, "records := make([]cmdwire.Record, 0, %d)\n", len(schema.Reply.Records)+1)
	for index, record := range schema.Reply.Records {
		fields := fmt.Sprintf("fields%d", index)
		fmt.Fprintf(output, "%s := make([]cmdwire.Field, 0)\n", fields)
		for _, field := range record.Fields {
			writeEncodeFieldWithPrefix(output, replyFieldName(index, record, field), field, fields)
		}
		fmt.Fprintf(output, "records = append(records, cmdwire.Record{Kind: cmdwire.%s, Command: Command%s, Resource: %q, Fields: %s})\n", kindName(record.Kind), name, record.Resource, fields)
	}
	fmt.Fprintln(output, `fields := []cmdwire.Field{
        {Name: "schema", Value: strconv.FormatUint(`+strconv.FormatUint(schema.Version, 10)+`, 10)},
        {Name: "count", Value: strconv.Itoa(len(records))},
    }`)
	for _, field := range schema.Reply.Terminal {
		writeEncodeFieldWithPrefix(output, "Terminal"+identifier(field.Name), field, "fields")
	}
	fmt.Fprintf(output, "records = append(records, cmdwire.Record{Kind: cmdwire.OK, Command: Command%s, Fields: fields})\n", name)
	fmt.Fprint(output, "return records\n}\n\n")
	fmt.Fprintf(output, "func (reply %sReply) Format() (string, error) {\n", name)
	fmt.Fprintln(output, "if err := reply.validate(); err != nil { return \"\", err }")
	fmt.Fprintln(output, "return formatRecords(reply.Records())")
	fmt.Fprintln(output, "}")
	fmt.Fprintf(output, "func (reply %sReply) validate() error {\n", name)
	writeReplyValidation(output, schema)
	fmt.Fprintln(output, "return nil")
	fmt.Fprint(output, "}\n\n")
}

func writeReplyValidation(output *bytes.Buffer, schema cmdwire.Schema) {
	for index, record := range schema.Reply.Records {
		for _, field := range record.Fields {
			writeFieldValidation(output, replyFieldName(index, record, field), field)
		}
	}
	for _, field := range schema.Reply.Terminal {
		writeFieldValidation(output, "Terminal"+identifier(field.Name), field)
	}
}

func writeFieldValidation(output *bytes.Buffer, target string, schema cmdwire.FieldSchema) {
	if !hasValueValidation(schema) {
		return
	}

	expression := "reply." + target
	if !schema.Required {
		fmt.Fprintf(output, "if %s != nil {\n", expression)
		expression = "*" + expression
	}
	if schema.Unavailable {
		fmt.Fprintf(output, "if %s.Available {\n", expression)
		expression += ".Value"
	}

	switch schema.Type {
	case "enum":
		fmt.Fprintf(output, "switch %s {\n", expression)
		fmt.Fprint(output, "case ")
		for index, value := range schema.Values {
			if index != 0 {
				fmt.Fprint(output, ", ")
			}
			fmt.Fprintf(output, "%q", value)
		}
		fmt.Fprintf(output, ":\ndefault:\nreturn fmt.Errorf(%q, %s)\n}\n", "invalid "+schema.Name+" %q", expression)
	case "uint":
		if schema.Minimum != nil && *schema.Minimum != 0 {
			fmt.Fprintf(output, "if %s < %d { return fmt.Errorf(%q, %s) }\n", expression, *schema.Minimum, "invalid "+schema.Name+" %d", expression)
		}
		if schema.Maximum != nil {
			fmt.Fprintf(output, "if %s > %d { return fmt.Errorf(%q, %s) }\n", expression, *schema.Maximum, "invalid "+schema.Name+" %d", expression)
		}
	case "hex":
		if schema.Width < 16 {
			maximum := uint64(1)<<(uint(schema.Width)*4) - 1
			fmt.Fprintf(output, "if %s > 0x%x { return fmt.Errorf(%q, %s) }\n", expression, maximum, "invalid "+schema.Name+" %x", expression)
		}
	}

	if schema.Unavailable {
		fmt.Fprintln(output, "}")
	}
	if !schema.Required {
		fmt.Fprintln(output, "}")
	}
}

func hasValueValidation(schema cmdwire.FieldSchema) bool {
	switch schema.Type {
	case "enum":
		return true
	case "uint":
		return (schema.Minimum != nil && *schema.Minimum != 0) || schema.Maximum != nil
	case "hex":
		return schema.Width < 16
	default:
		return false
	}
}

func writeSchema(output *bytes.Buffer, schema cmdwire.Schema) {
	fmt.Fprintf(output, "cmdwire.Schema{Format:%d, Command:%q, Version:%d, Request:", schema.Format, schema.Command, schema.Version)
	writeMessage(output, schema.Request)
	fmt.Fprint(output, ", Reply:cmdwire.ReplySchema{Records:[]cmdwire.RecordSchema{")
	for _, record := range schema.Reply.Records {
		fmt.Fprintf(output, "{Kind:cmdwire.%s, Resource:%q, Fields:", kindName(record.Kind), record.Resource)
		writeFields(output, record.Fields)
		fmt.Fprint(output, "},")
	}
	fmt.Fprint(output, "}, Terminal:")
	writeFields(output, schema.Reply.Terminal)
	fmt.Fprint(output, "}, Errors:[]cmdwire.ErrorSchema{")
	for _, errorSchema := range schema.Errors {
		fmt.Fprintf(output, "{Code:%q, Fields:", errorSchema.Code)
		writeFields(output, errorSchema.Fields)
		fmt.Fprint(output, "},")
	}
	fmt.Fprint(output, "}}")
}

func writeMessage(output *bytes.Buffer, message cmdwire.MessageSchema) {
	fmt.Fprintf(output, "cmdwire.MessageSchema{Resource:%q, Fields:", message.Resource)
	writeFields(output, message.Fields)
	fmt.Fprint(output, "}")
}

func writeFields(output *bytes.Buffer, fields []cmdwire.FieldSchema) {
	fmt.Fprint(output, "[]cmdwire.FieldSchema{")
	for _, field := range fields {
		fmt.Fprintf(output, "{Name:%q, Type:%q, Required:%t, Values:[]string{", field.Name, field.Type, field.Required)
		for _, value := range field.Values {
			fmt.Fprintf(output, "%q,", value)
		}
		fmt.Fprintf(output, "}, Width:%d, Unavailable:%t", field.Width, field.Unavailable)
		if field.Minimum != nil {
			fmt.Fprintf(output, ", Minimum:uint64Pointer(%d)", *field.Minimum)
		}
		if field.Maximum != nil {
			fmt.Fprintf(output, ", Maximum:uint64Pointer(%d)", *field.Maximum)
		}
		fmt.Fprint(output, "},")
	}
	fmt.Fprint(output, "}")
}

func writeDecodeField(output *bytes.Buffer, target string, schema cmdwire.FieldSchema) {
	value := fmt.Sprintf("field(record, %q)", schema.Name)
	if !schema.Required {
		fmt.Fprintf(output, "if value := %s; value != \"\" {\n", value)
		value = "value"
	}
	switch schema.Type {
	case "bool":
		fmt.Fprintf(output, "parsed, parseErr := strconv.ParseBool(%s); if parseErr != nil { err = parseErr; return }; %s = ", value, target)
		if schema.Required {
			fmt.Fprintln(output, "parsed")
		} else {
			fmt.Fprintln(output, "&parsed")
		}
	case "uint":
		fmt.Fprintf(output, "parsed, parseErr := strconv.ParseUint(%s, 10, 64); if parseErr != nil { err = parseErr; return }; %s = ", value, target)
		if schema.Required {
			fmt.Fprintln(output, "parsed")
		} else {
			fmt.Fprintln(output, "&parsed")
		}
	case "hex":
		fmt.Fprintf(output, "parsed, parseErr := strconv.ParseUint(%s[2:], 16, 64); if parseErr != nil { err = parseErr; return }; %s = ", value, target)
		if schema.Required {
			fmt.Fprintln(output, "parsed")
		} else {
			fmt.Fprintln(output, "&parsed")
		}
	default:
		if schema.Required {
			fmt.Fprintf(output, "%s = %s\n", target, value)
		} else {
			fmt.Fprintf(output, "parsed := %s; %s = &parsed\n", value, target)
		}
	}
	if !schema.Required {
		fmt.Fprintln(output, "}")
	}
}

func writeEncodeFieldWithPrefix(output *bytes.Buffer, target string, schema cmdwire.FieldSchema, fields string) {
	if !schema.Required {
		fmt.Fprintf(output, "if reply.%s != nil {\n", target)
	}
	if schema.Unavailable {
		value := identifier(target) + "Value"
		fmt.Fprintf(output, "%s := \"unavailable\"\nif reply.%s.Available { %s = strconv.FormatUint(reply.%s.Value, 10) }\n", value, target, value, target)
		fmt.Fprintf(output, "%s = append(%s, cmdwire.Field{Name:%q, Value:%s})\n", fields, fields, schema.Name, value)
		if !schema.Required {
			fmt.Fprintln(output, "}")
		}
		return
	}
	expression := "reply." + target
	if !schema.Required {
		expression = "*" + expression
	}
	switch schema.Type {
	case "bool":
		expression = "strconv.FormatBool(" + expression + ")"
	case "uint":
		expression = "strconv.FormatUint(" + expression + ", 10)"
	case "hex":
		expression = fmt.Sprintf("fmt.Sprintf(\"0x%%0%dx\", %s)", schema.Width, expression)
	}
	fmt.Fprintf(output, "%s = append(%s, cmdwire.Field{Name:%q, Value:%s})\n", fields, fields, schema.Name, expression)
	if !schema.Required {
		fmt.Fprintln(output, "}")
	}
}

func replyFieldName(index int, record cmdwire.RecordSchema, field cmdwire.FieldSchema) string {
	prefix := record.Resource
	if prefix == "" {
		prefix = fmt.Sprintf("record%d", index+1)
	}
	return identifier(prefix + "." + field.Name)
}

func goType(schema cmdwire.FieldSchema) string {
	base := "string"
	if schema.Unavailable {
		base = "UintValue"
	} else {
		switch schema.Type {
		case "bool":
			base = "bool"
		case "uint", "hex":
			base = "uint64"
		}
	}
	if !schema.Required {
		return "*" + base
	}
	return base
}

func kindName(kind cmdwire.Kind) string {
	switch kind {
	case cmdwire.Event:
		return "Event"
	case cmdwire.Item:
		return "Item"
	case cmdwire.Chunk:
		return "Chunk"
	default:
		panic("invalid data record kind")
	}
}

func identifier(input string) string {
	var output strings.Builder
	upperNext := true
	for _, char := range input {
		if !unicode.IsLetter(char) && !unicode.IsDigit(char) {
			upperNext = true
			continue
		}
		if upperNext {
			char = unicode.ToUpper(char)
			upperNext = false
		}
		output.WriteRune(char)
	}
	return output.String()
}
