package schemagen

import (
	"bytes"
	"fmt"
	"strconv"
	"strings"
	"unicode"

	"github.com/sartura/cmdwire"
)

// Rust generates one Rust source file containing no_std-compatible bindings
// for schemas. The generated source depends only on the cmdwire Rust crate.
func Rust(schemas []cmdwire.Schema) ([]byte, error) {
	seen := make(map[string]bool, len(schemas))
	seenNames := make(map[string]bool, len(schemas))
	for _, schema := range schemas {
		if err := schema.Validate(); err != nil {
			return nil, err
		}
		if seen[schema.Command] {
			return nil, fmt.Errorf("repeated command schema %q", schema.Command)
		}
		generatedName := rustTypeName(schema.Command)
		if seenNames[generatedName] {
			return nil, fmt.Errorf("generated Rust command name %q is repeated", generatedName)
		}
		seenNames[generatedName] = true
		if err := checkRustFieldNames("request", schema.Request.Fields); err != nil {
			return nil, err
		}
		for _, field := range schema.Request.Fields {
			if field.Type == "bytes" {
				return nil, fmt.Errorf("generated Rust does not support bytes request field %q", field.Name)
			}
			if field.Unavailable {
				return nil, fmt.Errorf("generated Rust does not support unavailable request field %q", field.Name)
			}
			if err := checkRustField(field); err != nil {
				return nil, err
			}
		}
		for index, record := range schema.Reply.Records {
			if err := checkRustFieldNames(fmt.Sprintf("reply record %d", index), record.Fields); err != nil {
				return nil, err
			}
			for _, field := range record.Fields {
				if err := checkRustField(field); err != nil {
					return nil, err
				}
			}
		}
		if err := checkRustFieldNames("reply terminal", schema.Reply.Terminal); err != nil {
			return nil, err
		}
		for _, field := range schema.Reply.Terminal {
			if err := checkRustField(field); err != nil {
				return nil, err
			}
		}
		seenVariants := make(map[string]bool, len(schema.Errors))
		for _, errorSchema := range schema.Errors {
			variant := rustTypeName(strings.ToLower(errorSchema.Code))
			if seenVariants[variant] {
				return nil, fmt.Errorf("generated Rust error variant %q is repeated", variant)
			}
			seenVariants[variant] = true
			if err := checkRustFieldNames("error "+errorSchema.Code, errorSchema.Fields); err != nil {
				return nil, err
			}
			for _, field := range errorSchema.Fields {
				if err := checkRustField(field); err != nil {
					return nil, err
				}
			}
		}
		if err := checkRustReplyNames(schema); err != nil {
			return nil, err
		}
		seen[schema.Command] = true
	}

	var output bytes.Buffer
	fmt.Fprintln(&output, "// Code generated by cmdwire; DO NOT EDIT.")
	fmt.Fprintln(&output)
	for _, schema := range schemas {
		generateRustSchema(&output, schema)
	}
	generateRustDispatch(&output, schemas)
	return output.Bytes(), nil
}

func generateRustDispatch(output *bytes.Buffer, schemas []cmdwire.Schema) {
	fmt.Fprintln(output, "pub const COMMAND_NAMES: &[&str] = &[")
	for _, schema := range schemas {
		fmt.Fprintf(output, "    %s,\n", "COMMAND_"+rustConstantName(schema.Command))
	}
	fmt.Fprintln(output, "];")
	fmt.Fprintln(output)
	borrowed := false
	for _, schema := range schemas {
		borrowed = borrowed || hasBorrowed(schema.Request.Fields)
	}
	fmt.Fprintln(output, "#[allow(clippy::enum_variant_names)]")
	fmt.Fprintln(output, "#[derive(Clone, Copy, Debug, Eq, PartialEq)]")
	fmt.Fprintf(output, "pub enum DecodedCommand%s {\n", rustLifetime(borrowed))
	for _, schema := range schemas {
		typeName := rustTypeName(schema.Command)
		fmt.Fprintf(output, "    %s(%sRequest%s),\n", typeName, typeName, rustUseLifetime(hasBorrowed(schema.Request.Fields)))
	}
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
	fmt.Fprintf(output, "pub fn decode_command<'a>(record: ::cmdwire::Record<'a>) -> Result<DecodedCommand%s, ::cmdwire::DecodeError> {\n", rustUseLifetime(borrowed))
	fmt.Fprintln(output, "    match record.command() {")
	for _, schema := range schemas {
		typeName := rustTypeName(schema.Command)
		constant := "COMMAND_" + rustConstantName(schema.Command)
		functionName := "decode_" + rustFieldName(schema.Command)
		fmt.Fprintf(output, "        %s => Ok(DecodedCommand::%s(%s(record)?)),\n", constant, typeName, functionName)
	}
	fmt.Fprintln(output, "        _ => Err(::cmdwire::DecodeError::UnknownCommand),")
	fmt.Fprintln(output, "    }")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
}

func checkRustField(field cmdwire.FieldSchema) error {
	if field.Unavailable && field.Type != "uint" {
		return fmt.Errorf("generated Rust supports unavailable only for uint field %q", field.Name)
	}
	if field.Type == "hex" && field.Width > 16 {
		return fmt.Errorf("generated Rust hex field %q exceeds 64 bits", field.Name)
	}
	return nil
}

func checkRustFieldNames(context string, fields []cmdwire.FieldSchema) error {
	seen := make(map[string]bool, len(fields))
	for _, field := range fields {
		name := rustFieldName(field.Name)
		if seen[name] {
			return fmt.Errorf("generated Rust %s field name %q is repeated", context, name)
		}
		seen[name] = true
	}
	return nil
}

func checkRustReplyNames(schema cmdwire.Schema) error {
	seen := make(map[string]bool)
	seenMethods := make(map[string]bool)
	for index, record := range schema.Reply.Records {
		if hasStreamingReply(schema) {
			method := rustStreamRecordName(index, record)
			if seenMethods[method] {
				return fmt.Errorf("generated Rust streaming reply method %q is repeated", method)
			}
			seenMethods[method] = true
		}
		for _, field := range record.Fields {
			name := rustReplyFieldName(index, record, field)
			if seen[name] {
				return fmt.Errorf("generated Rust reply field name %q is repeated", name)
			}
			seen[name] = true
		}
	}
	for _, field := range schema.Reply.Terminal {
		name := "terminal_" + rustFieldName(field.Name)
		if seen[name] {
			return fmt.Errorf("generated Rust reply field name %q is repeated", name)
		}
		seen[name] = true
	}
	return nil
}

func generateRustSchema(output *bytes.Buffer, schema cmdwire.Schema) {
	typeName := rustTypeName(schema.Command)
	constant := "COMMAND_" + rustConstantName(schema.Command)
	fmt.Fprintf(output, "pub const %s: &str = %s;\n\n", constant, strconv.Quote(schema.Command))
	generateRustRequest(output, schema, typeName, constant)
	generateRustReply(output, schema, typeName, constant)
	if len(schema.Errors) != 0 {
		generateRustErrors(output, schema, typeName, constant)
	}
}

func generateRustRequest(output *bytes.Buffer, schema cmdwire.Schema, typeName, constant string) {
	borrowed := hasBorrowed(schema.Request.Fields)
	lifetime := rustLifetime(borrowed)
	fmt.Fprintln(output, "#[derive(Clone, Copy, Debug, Eq, PartialEq)]")
	fmt.Fprintf(output, "pub struct %sRequest%s {\n", typeName, lifetime)
	for _, field := range schema.Request.Fields {
		fmt.Fprintf(output, "    pub %s: %s,\n", rustFieldName(field.Name), rustType(field))
	}
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)

	functionName := "decode_" + rustFieldName(schema.Command)
	fmt.Fprintf(output, "pub fn %s<'a>(record: ::cmdwire::Record<'a>) -> Result<%sRequest%s, ::cmdwire::DecodeError> {\n", functionName, typeName, rustUseLifetime(borrowed))
	fmt.Fprintln(output, "    if record.kind() != ::cmdwire::Kind::Request {")
	fmt.Fprintln(output, "        return Err(::cmdwire::DecodeError::WrongKind);")
	fmt.Fprintln(output, "    }")
	fmt.Fprintf(output, "    if record.command() != %s {\n", constant)
	fmt.Fprintln(output, "        return Err(::cmdwire::DecodeError::WrongCommand);")
	fmt.Fprintln(output, "    }")
	if schema.Request.Resource == "" {
		fmt.Fprintln(output, "    if record.resource().is_some() {")
	} else {
		fmt.Fprintf(output, "    if record.resource() != Some(%s) {\n", strconv.Quote(schema.Request.Resource))
	}
	fmt.Fprintln(output, "        return Err(::cmdwire::DecodeError::WrongResource);")
	fmt.Fprintln(output, "    }")
	fmt.Fprintln(output, "    let mut fields = record.fields().peekable();")
	for _, field := range schema.Request.Fields {
		writeRustDecodeField(output, field)
	}
	fmt.Fprintln(output, "    if fields.next().is_some() {")
	fmt.Fprintln(output, "        return Err(::cmdwire::DecodeError::UnexpectedField);")
	fmt.Fprintln(output, "    }")
	fmt.Fprintf(output, "    Ok(%sRequest {\n", typeName)
	for _, field := range schema.Request.Fields {
		name := rustFieldName(field.Name)
		fmt.Fprintf(output, "        %s,\n", name)
	}
	fmt.Fprintln(output, "    })")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
}

func writeRustDecodeField(output *bytes.Buffer, field cmdwire.FieldSchema) {
	name := rustFieldName(field.Name)
	wireName := strconv.Quote(field.Name)
	if field.Required {
		fmt.Fprintln(output, "    let field = fields")
		fmt.Fprintln(output, "        .next()")
		fmt.Fprintf(output, "        .filter(|field| field.name == %s)\n", wireName)
		fmt.Fprintf(output, "        .ok_or(::cmdwire::DecodeError::MissingField(%s))?;\n", wireName)
		fmt.Fprintf(output, "    let %s = %s;\n", name, rustDecodeExpression(field, "field.value"))
		return
	}
	fmt.Fprintf(output, "    let %s = if fields.peek().is_some_and(|field| field.name == %s) {\n", name, wireName)
	fmt.Fprintln(output, "        let field = fields.next().expect(\"peeked field exists\");")
	fmt.Fprintf(output, "        Some(%s)\n", rustDecodeExpression(field, "field.value"))
	fmt.Fprintln(output, "    } else {")
	fmt.Fprintln(output, "        None")
	fmt.Fprintln(output, "    };")
}

func rustDecodeExpression(field cmdwire.FieldSchema, value string) string {
	name := strconv.Quote(field.Name)
	switch field.Type {
	case "token":
		return value
	case "bool":
		return fmt.Sprintf("::cmdwire::decode_bool(%s, %s)?", name, value)
	case "uint":
		return fmt.Sprintf("::cmdwire::decode_uint(%s, %s, %s, %s)?", name, value, rustOptionUint(field.Minimum), rustOptionUint(field.Maximum))
	case "enum":
		return fmt.Sprintf("::cmdwire::decode_enum(%s, %s, %s)?", name, value, rustStringSlice(field.Values))
	case "hex":
		return fmt.Sprintf("::cmdwire::decode_hex(%s, %s, %d)?", name, value, field.Width)
	default:
		panic("unsupported field type")
	}
}

func generateRustReply(output *bytes.Buffer, schema cmdwire.Schema, typeName, constant string) {
	if hasStreamingReply(schema) {
		generateRustStreamingReply(output, schema, typeName, constant)
		return
	}
	generateRustFixedReply(output, schema, typeName, constant)
}

func generateRustFixedReply(output *bytes.Buffer, schema cmdwire.Schema, typeName, constant string) {
	fields := rustReplyFields(schema)
	borrowed := hasNamedBorrowed(fields)
	fmt.Fprintln(output, "#[derive(Clone, Copy, Debug, Eq, PartialEq)]")
	fmt.Fprintf(output, "pub struct %sReply%s {\n", typeName, rustLifetime(borrowed))
	for _, field := range fields {
		fmt.Fprintf(output, "    pub %s: %s,\n", field.name, rustType(field.schema))
	}
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
	fmt.Fprintf(output, "impl%s %sReply%s {\n", rustImplLifetime(borrowed), typeName, rustUseLifetime(borrowed))
	fmt.Fprintf(output, "    pub fn encode(&self) -> Result<[::cmdwire::Line; %d], ::cmdwire::EncodeError> {\n", len(schema.Reply.Records)+1)
	fieldIndex := 0
	for index, record := range schema.Reply.Records {
		names := make([]string, 0, len(record.Fields))
		for range record.Fields {
			field := fields[fieldIndex]
			writeRustEncodeLocal(output, field.name, "self."+field.name, field.schema)
			names = append(names, field.name)
			fieldIndex++
		}
		fmt.Fprintf(output, "        let record_%d = ::cmdwire::encode_record(\n", index)
		fmt.Fprintf(output, "            ::cmdwire::Kind::%s,\n", rustKind(record.Kind))
		fmt.Fprintf(output, "            %s,\n", constant)
		fmt.Fprintf(output, "            %s,\n", rustOptionString(record.Resource))
		fmt.Fprintf(output, "            [%s],\n", rustFieldOptions(names, record.Fields))
		fmt.Fprintln(output, "        )?;")
	}

	terminalNames := []string{"schema", "count"}
	fmt.Fprintf(output, "        let schema = ::cmdwire::WireField::uint(\"schema\", %d);\n", schema.Version)
	fmt.Fprintf(output, "        let count = ::cmdwire::WireField::uint(\"count\", %d);\n", len(schema.Reply.Records))
	for range schema.Reply.Terminal {
		field := fields[fieldIndex]
		writeRustEncodeLocal(output, field.name, "self."+field.name, field.schema)
		terminalNames = append(terminalNames, field.name)
		fieldIndex++
	}
	fmt.Fprintln(output, "        let terminal = ::cmdwire::encode_record(")
	fmt.Fprintln(output, "            ::cmdwire::Kind::Ok,")
	fmt.Fprintf(output, "            %s,\n", constant)
	fmt.Fprintln(output, "            None,")
	terminalSchemas := append([]cmdwire.FieldSchema{{Name: "schema", Required: true}, {Name: "count", Required: true}}, schema.Reply.Terminal...)
	fmt.Fprintf(output, "            [%s],\n", rustFieldOptions(terminalNames, terminalSchemas))
	fmt.Fprintln(output, "        )?;")
	fmt.Fprint(output, "        Ok([")
	for index := range schema.Reply.Records {
		fmt.Fprintf(output, "record_%d, ", index)
	}
	fmt.Fprintln(output, "terminal])")
	fmt.Fprintln(output, "    }")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
}

func hasStreamingReply(schema cmdwire.Schema) bool {
	for _, record := range schema.Reply.Records {
		if record.Occurs != nil {
			return true
		}
	}
	return false
}

func generateRustStreamingReply(output *bytes.Buffer, schema cmdwire.Schema, typeName, constant string) {
	for index, record := range schema.Reply.Records {
		recordType := rustStreamRecordType(typeName, index, record)
		borrowed := hasBorrowed(record.Fields)
		fmt.Fprintln(output, "#[derive(Clone, Copy, Debug, Eq, PartialEq)]")
		fmt.Fprintf(output, "pub struct %s%s {\n", recordType, rustLifetime(borrowed))
		for _, field := range record.Fields {
			fmt.Fprintf(output, "    pub %s: %s,\n", rustFieldName(field.Name), rustType(field))
		}
		fmt.Fprintln(output, "}")
		fmt.Fprintln(output)
	}
	terminalBorrowed := hasBorrowed(schema.Reply.Terminal)
	if len(schema.Reply.Terminal) != 0 {
		fmt.Fprintln(output, "#[derive(Clone, Copy, Debug, Eq, PartialEq)]")
		fmt.Fprintf(output, "pub struct %sReplyTerminal%s {\n", typeName, rustLifetime(terminalBorrowed))
		for _, field := range schema.Reply.Terminal {
			fmt.Fprintf(output, "    pub %s: %s,\n", rustFieldName(field.Name), rustType(field))
		}
		fmt.Fprintln(output, "}")
		fmt.Fprintln(output)
	}

	fmt.Fprintln(output, "#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]")
	fmt.Fprintf(output, "pub struct %sReply {\n", typeName)
	fmt.Fprintf(output, "    occurrences: [u64; %d],\n", len(schema.Reply.Records))
	fmt.Fprintln(output, "    count: u64,")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
	fmt.Fprintf(output, "impl %sReply {\n", typeName)
	fmt.Fprintln(output, "    pub const fn new() -> Self {")
	fmt.Fprintf(output, "        Self { occurrences: [0; %d], count: 0 }\n", len(schema.Reply.Records))
	fmt.Fprintln(output, "    }")
	fmt.Fprintln(output)

	for index, record := range schema.Reply.Records {
		recordType := rustStreamRecordType(typeName, index, record)
		borrowed := hasBorrowed(record.Fields)
		method := "push_" + rustStreamRecordName(index, record)
		fmt.Fprintf(output, "    pub fn %s%s(&mut self, record: %s%s) -> Result<::cmdwire::Line, ::cmdwire::EncodeError> {\n", method, rustMethodLifetime(borrowed), recordType, rustUseLifetime(borrowed))
		conditions := make([]string, 0, len(schema.Reply.Records)+1)
		for previous := 0; previous < index; previous++ {
			minimum, _ := rustOccurrenceBounds(schema.Reply.Records[previous])
			conditions = append(conditions, fmt.Sprintf("self.occurrences[%d] < %d", previous, minimum))
		}
		for later := index + 1; later < len(schema.Reply.Records); later++ {
			conditions = append(conditions, fmt.Sprintf("self.occurrences[%d] != 0", later))
		}
		_, maximum := rustOccurrenceBounds(record)
		if maximum != nil {
			conditions = append(conditions, fmt.Sprintf("self.occurrences[%d] >= %d", index, *maximum))
		}
		if len(conditions) != 0 {
			fmt.Fprintf(output, "        if %s {\n", strings.Join(conditions, " || "))
			fmt.Fprintln(output, "            return Err(::cmdwire::EncodeError::InvalidReplyState);")
			fmt.Fprintln(output, "        }")
		}
		names := make([]string, 0, len(record.Fields))
		for _, field := range record.Fields {
			name := rustFieldName(field.Name)
			writeRustEncodeLocal(output, name, "record."+name, field)
			names = append(names, name)
		}
		fmt.Fprintln(output, "        let line = ::cmdwire::encode_record(")
		fmt.Fprintf(output, "            ::cmdwire::Kind::%s,\n", rustKind(record.Kind))
		fmt.Fprintf(output, "            %s,\n", constant)
		fmt.Fprintf(output, "            %s,\n", rustOptionString(record.Resource))
		fmt.Fprintf(output, "            [%s],\n", rustFieldOptions(names, record.Fields))
		fmt.Fprintln(output, "        )?;")
		fmt.Fprintf(output, "        self.occurrences[%d] = self.occurrences[%d].checked_add(1).ok_or(::cmdwire::EncodeError::InvalidReplyState)?;\n", index, index)
		fmt.Fprintln(output, "        self.count = self.count.checked_add(1).ok_or(::cmdwire::EncodeError::InvalidReplyState)?;")
		fmt.Fprintln(output, "        Ok(line)")
		fmt.Fprintln(output, "    }")
		fmt.Fprintln(output)
	}

	if len(schema.Reply.Terminal) == 0 {
		fmt.Fprintln(output, "    pub fn finish(self) -> Result<::cmdwire::Line, ::cmdwire::EncodeError> {")
	} else {
		fmt.Fprintf(output, "    pub fn finish%s(self, terminal_fields: %sReplyTerminal%s) -> Result<::cmdwire::Line, ::cmdwire::EncodeError> {\n", rustMethodLifetime(terminalBorrowed), typeName, rustUseLifetime(terminalBorrowed))
	}
	minimumConditions := make([]string, 0, len(schema.Reply.Records))
	for index, record := range schema.Reply.Records {
		minimum, _ := rustOccurrenceBounds(record)
		if minimum != 0 {
			minimumConditions = append(minimumConditions, fmt.Sprintf("self.occurrences[%d] < %d", index, minimum))
		}
	}
	if len(minimumConditions) != 0 {
		fmt.Fprintf(output, "        if %s {\n", strings.Join(minimumConditions, " || "))
		fmt.Fprintln(output, "            return Err(::cmdwire::EncodeError::InvalidReplyState);")
		fmt.Fprintln(output, "        }")
	}
	terminalNames := []string{"schema", "count"}
	fmt.Fprintf(output, "        let schema = ::cmdwire::WireField::uint(\"schema\", %d);\n", schema.Version)
	fmt.Fprintln(output, "        let count = ::cmdwire::WireField::uint(\"count\", self.count);")
	for _, field := range schema.Reply.Terminal {
		name := rustFieldName(field.Name)
		writeRustEncodeLocal(output, name, "terminal_fields."+name, field)
		terminalNames = append(terminalNames, name)
	}
	terminalSchemas := append([]cmdwire.FieldSchema{{Name: "schema", Required: true}, {Name: "count", Required: true}}, schema.Reply.Terminal...)
	fmt.Fprintln(output, "        ::cmdwire::encode_record(")
	fmt.Fprintln(output, "            ::cmdwire::Kind::Ok,")
	fmt.Fprintf(output, "            %s,\n", constant)
	fmt.Fprintln(output, "            None,")
	fmt.Fprintf(output, "            [%s],\n", rustFieldOptions(terminalNames, terminalSchemas))
	fmt.Fprintln(output, "        )")
	fmt.Fprintln(output, "    }")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
}

func rustOccurrenceBounds(record cmdwire.RecordSchema) (uint64, *uint64) {
	if record.Occurs != nil {
		return record.Occurs.Minimum, record.Occurs.Maximum
	}
	one := uint64(1)
	return one, &one
}

func rustStreamRecordName(index int, record cmdwire.RecordSchema) string {
	if record.Resource != "" {
		return rustFieldName(record.Resource)
	}
	return fmt.Sprintf("record_%d", index+1)
}

func rustStreamRecordType(typeName string, index int, record cmdwire.RecordSchema) string {
	name := record.Resource
	if name == "" {
		name = fmt.Sprintf("record%d", index+1)
	}
	return typeName + "Reply" + rustTypeName(name)
}

func rustMethodLifetime(borrowed bool) string {
	if borrowed {
		return "<'a>"
	}
	return ""
}

type rustNamedField struct {
	name   string
	schema cmdwire.FieldSchema
}

func rustReplyFields(schema cmdwire.Schema) []rustNamedField {
	var fields []rustNamedField
	for index, record := range schema.Reply.Records {
		for _, field := range record.Fields {
			fields = append(fields, rustNamedField{name: rustReplyFieldName(index, record, field), schema: field})
		}
	}
	for _, field := range schema.Reply.Terminal {
		fields = append(fields, rustNamedField{name: "terminal_" + rustFieldName(field.Name), schema: field})
	}
	return fields
}

func generateRustErrors(output *bytes.Buffer, schema cmdwire.Schema, typeName, constant string) {
	borrowed := false
	for _, errorSchema := range schema.Errors {
		borrowed = borrowed || hasBorrowed(errorSchema.Fields)
	}
	fmt.Fprintln(output, "#[derive(Clone, Copy, Debug, Eq, PartialEq)]")
	fmt.Fprintf(output, "pub enum %sError%s {\n", typeName, rustLifetime(borrowed))
	for _, errorSchema := range schema.Errors {
		variant := rustTypeName(strings.ToLower(errorSchema.Code))
		if len(errorSchema.Fields) == 0 {
			fmt.Fprintf(output, "    %s,\n", variant)
			continue
		}
		fmt.Fprintf(output, "    %s {\n", variant)
		for _, field := range errorSchema.Fields {
			fmt.Fprintf(output, "        %s: %s,\n", rustFieldName(field.Name), rustType(field))
		}
		fmt.Fprintln(output, "    },")
	}
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
	fmt.Fprintf(output, "impl%s %sError%s {\n", rustImplLifetime(borrowed), typeName, rustUseLifetime(borrowed))
	fmt.Fprintln(output, "    pub fn encode(&self) -> Result<::cmdwire::Line, ::cmdwire::EncodeError> {")
	fmt.Fprintln(output, "        match *self {")
	for _, errorSchema := range schema.Errors {
		variant := rustTypeName(strings.ToLower(errorSchema.Code))
		fieldNames := make([]string, 0, len(errorSchema.Fields)+1)
		fieldNames = append(fieldNames, "code")
		if len(errorSchema.Fields) == 0 {
			fmt.Fprintf(output, "            Self::%s => {\n", variant)
		} else {
			fmt.Fprintf(output, "            Self::%s { ", variant)
			for _, field := range errorSchema.Fields {
				fmt.Fprintf(output, "%s, ", rustFieldName(field.Name))
			}
			fmt.Fprintln(output, "} => {")
		}
		fmt.Fprintf(output, "                let code = ::cmdwire::WireField::token(\"code\", %s);\n", strconv.Quote(errorSchema.Code))
		for _, field := range errorSchema.Fields {
			name := rustFieldName(field.Name)
			writeRustEncodeLocalIndented(output, name, name, field, "                ")
			fieldNames = append(fieldNames, name)
		}
		schemas := append([]cmdwire.FieldSchema{{Name: "code", Required: true}}, errorSchema.Fields...)
		fmt.Fprintln(output, "                ::cmdwire::encode_record(")
		fmt.Fprintln(output, "                    ::cmdwire::Kind::Error,")
		fmt.Fprintf(output, "                    %s,\n", constant)
		fmt.Fprintln(output, "                    None,")
		fmt.Fprintf(output, "                    [%s],\n", rustFieldOptions(fieldNames, schemas))
		fmt.Fprintln(output, "                )")
		fmt.Fprintln(output, "            }")
	}
	fmt.Fprintln(output, "        }")
	fmt.Fprintln(output, "    }")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
}

func writeRustEncodeLocal(output *bytes.Buffer, name, expression string, field cmdwire.FieldSchema) {
	writeRustEncodeLocalIndented(output, name, expression, field, "        ")
}

func writeRustEncodeLocalIndented(output *bytes.Buffer, name, expression string, field cmdwire.FieldSchema, indent string) {
	if field.Required {
		fmt.Fprintf(output, "%slet %s = %s;\n", indent, name, rustEncodeExpression(field, expression))
		return
	}
	fmt.Fprintf(output, "%slet %s = %s\n", indent, name, expression)
	fmt.Fprintf(output, "%s    .map(|value| Ok::<_, ::cmdwire::EncodeError>(%s))\n", indent, rustEncodeExpression(field, "value"))
	fmt.Fprintf(output, "%s    .transpose()?;\n", indent)
}

func rustEncodeExpression(field cmdwire.FieldSchema, expression string) string {
	name := strconv.Quote(field.Name)
	if field.Unavailable {
		return fmt.Sprintf("match %s { ::cmdwire::Available::Value(value) => ::cmdwire::WireField::uint(%s, ::cmdwire::validate_uint(%s, value, %s, %s)?), ::cmdwire::Available::Unavailable => ::cmdwire::WireField::token(%s, \"unavailable\") }", expression, name, name, rustOptionUint(field.Minimum), rustOptionUint(field.Maximum), name)
	}
	switch field.Type {
	case "token":
		return fmt.Sprintf("::cmdwire::WireField::token(%s, %s)", name, expression)
	case "bytes":
		return fmt.Sprintf("::cmdwire::WireField::bytes(%s, %s)", name, expression)
	case "bool":
		return fmt.Sprintf("::cmdwire::WireField::boolean(%s, %s)", name, expression)
	case "uint":
		return fmt.Sprintf("::cmdwire::WireField::uint(%s, ::cmdwire::validate_uint(%s, %s, %s, %s)?)", name, name, expression, rustOptionUint(field.Minimum), rustOptionUint(field.Maximum))
	case "enum":
		return fmt.Sprintf("::cmdwire::WireField::token(%s, ::cmdwire::validate_enum(%s, %s, %s)?)", name, name, expression, rustStringSlice(field.Values))
	case "hex":
		return fmt.Sprintf("::cmdwire::WireField::hex(%s, ::cmdwire::validate_hex(%s, %s, %d)?, %d)", name, name, expression, field.Width, field.Width)
	default:
		panic("unsupported field type")
	}
}

func rustFieldOptions(names []string, schemas []cmdwire.FieldSchema) string {
	parts := make([]string, len(names))
	for index, name := range names {
		if schemas[index].Required || name == "schema" || name == "count" || name == "code" {
			parts[index] = "Some(" + name + ")"
		} else {
			parts[index] = name
		}
	}
	return strings.Join(parts, ", ")
}

func rustType(field cmdwire.FieldSchema) string {
	base := "&'a str"
	if field.Type == "bytes" {
		base = "&'a [u8]"
	} else if field.Unavailable {
		base = "::cmdwire::Available<u64>"
	} else {
		switch field.Type {
		case "bool":
			base = "bool"
		case "uint", "hex":
			base = "u64"
		}
	}
	if !field.Required {
		return "Option<" + base + ">"
	}
	return base
}

func hasBorrowed(fields []cmdwire.FieldSchema) bool {
	for _, field := range fields {
		if field.Type == "token" || field.Type == "enum" || field.Type == "bytes" {
			return true
		}
	}
	return false
}

func hasNamedBorrowed(fields []rustNamedField) bool {
	for _, field := range fields {
		if field.schema.Type == "token" || field.schema.Type == "enum" || field.schema.Type == "bytes" {
			return true
		}
	}
	return false
}

func rustLifetime(borrowed bool) string {
	if borrowed {
		return "<'a>"
	}
	return ""
}

func rustUseLifetime(borrowed bool) string { return rustLifetime(borrowed) }

func rustImplLifetime(borrowed bool) string {
	if borrowed {
		return "<'a>"
	}
	return ""
}

func rustKind(kind cmdwire.Kind) string {
	switch kind {
	case cmdwire.Event:
		return "Event"
	case cmdwire.Item:
		return "Item"
	case cmdwire.Chunk:
		return "Chunk"
	default:
		panic("invalid data record kind")
	}
}

func rustReplyFieldName(index int, record cmdwire.RecordSchema, field cmdwire.FieldSchema) string {
	prefix := record.Resource
	if prefix == "" {
		prefix = fmt.Sprintf("record%d", index+1)
	}
	return rustFieldName(prefix + "." + field.Name)
}

func rustTypeName(input string) string {
	name := identifier(input)
	if name == "Self" {
		return "SelfValue"
	}
	return name
}

func rustFieldName(input string) string {
	var output strings.Builder
	lastUnderscore := false
	for _, char := range input {
		if unicode.IsLetter(char) || unicode.IsDigit(char) {
			output.WriteRune(unicode.ToLower(char))
			lastUnderscore = false
		} else if !lastUnderscore {
			output.WriteByte('_')
			lastUnderscore = true
		}
	}
	name := strings.Trim(output.String(), "_")
	if name == "" {
		name = "field"
	}
	if name[0] >= '0' && name[0] <= '9' {
		name = "_" + name
	}
	if rustKeywords[name] {
		name += "_"
	}
	return name
}

func rustConstantName(input string) string {
	var output strings.Builder
	lastUnderscore := false
	for _, char := range input {
		if unicode.IsLetter(char) || unicode.IsDigit(char) {
			output.WriteRune(unicode.ToUpper(char))
			lastUnderscore = false
		} else if !lastUnderscore {
			output.WriteByte('_')
			lastUnderscore = true
		}
	}
	return strings.Trim(output.String(), "_")
}

func rustOptionUint(value *uint64) string {
	if value == nil {
		return "None"
	}
	return fmt.Sprintf("Some(%d)", *value)
}

func rustOptionString(value string) string {
	if value == "" {
		return "None"
	}
	return "Some(" + strconv.Quote(value) + ")"
}

func rustStringSlice(values []string) string {
	quoted := make([]string, len(values))
	for index, value := range values {
		quoted[index] = strconv.Quote(value)
	}
	return "&[" + strings.Join(quoted, ", ") + "]"
}

var rustKeywords = map[string]bool{
	"as": true, "break": true, "const": true, "continue": true, "crate": true,
	"else": true, "enum": true, "extern": true, "false": true, "fn": true,
	"for": true, "if": true, "impl": true, "in": true, "let": true,
	"loop": true, "match": true, "mod": true, "move": true, "mut": true,
	"pub": true, "ref": true, "return": true, "self": true, "Self": true,
	"static": true, "struct": true, "super": true, "trait": true, "true": true,
	"type": true, "unsafe": true, "use": true, "where": true, "while": true,
	"async": true, "await": true, "dyn": true, "abstract": true, "become": true,
	"box": true, "do": true, "final": true, "macro": true, "override": true,
	"priv": true, "typeof": true, "unsized": true, "virtual": true, "yield": true,
	"try": true,
}
